version: '3.8'
services:
  postgres-catalog:
    image: postgres:15
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

